# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.lals1.github.io/
title: Shankar Lal
email: sl@gmail.com
author: Shankar Lal
description: > # "Shankar Lal's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/shankar-lal/
  - icon: flask
    title: scholar
    url: https://scholar.google.com/citations?user=-caizxYAAAAJ&hl=en
  - icon: github
    title: github
    url: https://github.com/lals1
#  - icon: instagram
#    title: life
#    url: https://www.instagram.com/wesleyy.c
#  - icon: file-pdf-o
#    title: resume
#    url: www.lals1.github.io
  - icon: envelope-o
    title: email
    url: mailto:sl@gmail.com
